### numpyの基礎的な使い方
<インストール方法>  
pip install numpy  

jupyter notebookの場合  
!pip install numpy  

#### Step1 numpyを読み込む

In [1]:
import numpy as np

#### Step2 numpyでデータを作る
numpyのデータを作るにはいくつか方法がありので、説明していきます。

Step2-1 0、1、乱数を作る

In [2]:
# 0のデータ
data = np.zeros([5,3])
print(data)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# 1のデータ
data = np.ones([5,3])
print(data)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# 乱数
data = np.random.rand(5,3)
print(data)

[[0.84859354 0.43623774 0.94162871]
 [0.14251071 0.33865027 0.27426747]
 [0.43650661 0.94247072 0.1083362 ]
 [0.08649675 0.21900527 0.37974148]
 [0.81746888 0.63316293 0.92725607]]


In [5]:
# 型はndarrayというのもになります。
print(type(data))

<class 'numpy.ndarray'>


In [6]:
# データの形はshapeで確認
print(data.shape)

(5, 3)


Step2-2 list、tuple、dictから作る

In [7]:
# listデータから
list_data = [[1,2,3],
             [4,5,6],
             [7,8,9]]
data = np.array(list_data)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# tupleデータから
tuple_data = ((1,2,3),
              (4,5,6),
              (7,8,9))
data = np.array(tuple_data)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# dictデータから
dcit_data = {'a':[1,2,3],
             'b':[4,5,6],
             'c':[7,8,9]}
# 一旦リストデータに変換 a,b,cのkey情報は消える
list_data = [dcit_data[k] for k in dcit_data.keys()]
data = np.array(list_data)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Step2-3 データを読み込む

In [10]:
# テキストファイルから
with open('sample_data.txt') as f:
    list_data = [d.rstrip() for d in f.readlines()]
data = np.array(list_data)
print(data)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [11]:
# CSVファイルから
with open('sample_data.csv') as f:
    list_data = [d.rstrip().split(',') for d in f.readlines()]
data = np.array(list_data)
print(data)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [12]:
# 画像データから
import cv2
img = cv2.imread('cat.jpg')
print('画像サイズ', img.shape)
print('データタイプ', type(img))

画像サイズ (640, 613, 3)
データタイプ <class 'numpy.ndarray'>


#### Step3 データを計算する

Step3-1 同じ行列数同士

In [13]:
# 四則演算
data1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
data2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
data = data1 + data2
print(data)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Step3-2 ブロードキャスト
data2が1つの数値だったり、data1と行列数が違ったらどうでしょう？

In [14]:
# 数値が1つ
data1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
data2 = -1

data = data1 + data2
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# 列数が合っている
data1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
data2 = [-1,-2,-3]

data = data1 + data2
print(data)

[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [16]:
# 行数があっている
data1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
data2 = [[-1],[-2],[-3]]

data = data1 + data2
print(data)

[[0 1 2]
 [2 3 4]
 [4 5 6]]


In [17]:
# 行列演算
data1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
data2 = [[-1],[-2],[-3]]

data = np.dot(data1, data2)
print(data)

[[-14]
 [-32]
 [-50]]
